base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: given_data/winequality.csv

load_data:
  raw_dataset_csv: data/raw/winequality.csv

split_data:
  train_path: data/preprocessed/train_winequality.csv
  test_path: data/preprocessed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
     # alpha: 0.88
     # l1_ratio: 0.89
      alpha: 0.8
      l1_ratio: 0.4

model_dir: saved_models

reports:
  params: Reports/params.json
  scores: Reports/scores.json